import type { DemoEvent } from '../entities';

export const demoEvents: DemoEvent[] = [
  {
    id: 'evt-leave-request',
    type: 'parent_leave_request',
    title: '张小雨请假申请待审批',
    summary: '家长已提交上午请假申请，等待班主任确认。',
    level: 'medium',
    status: 'processing',
    schoolId: 'school-hz-01',
    classId: 'class-g7-2',
    studentId: 'student-zhangxiaoyu',
    actorUserId: 'parent-zhangnvshi',
    ownerUserId: 'teacher-lin',
    source: 'parent',
    createdAt: '2026-06-19T08:12:00+08:00',
    updatedAt: '2026-06-19T08:12:00+08:00',
  },
  {
    id: 'evt-gate-pass',
    type: 'access_pass',
    title: '张小雨已完成入校通行',
    summary: '校门闸机记录到正常通行事件。',
    level: 'low',
    status: 'closed',
    schoolId: 'school-hz-01',
    classId: 'class-g7-2',
    studentId: 'student-zhangxiaoyu',
    relatedPointId: 'point-gate-east',
    source: 'system',
    createdAt: '2026-06-19T07:58:00+08:00',
    updatedAt: '2026-06-19T07:58:00+08:00',
  },
  {
    id: 'evt-gate-alert',
    type: 'access_alert',
    title: '陌生人闸机告警待确认',
    summary: '西门闸机识别到未登记人员，请安保确认。',
    level: 'high',
    status: 'pending',
    schoolId: 'school-hz-01',
    relatedPointId: 'point-gate-west',
    ownerUserId: 'admin-chen',
    source: 'mock-ai',
    createdAt: '2026-06-19T08:05:00+08:00',
    updatedAt: '2026-06-19T08:05:00+08:00',
  },
  {
    id: 'evt-patrol-east-building',
    type: 'patrol_risk',
    title: '东教学楼晨检完成',
    summary: '重点区域巡检正常，无异常上报。',
    level: 'low',
    status: 'closed',
    schoolId: 'school-hz-01',
    relatedPointId: 'point-east-building',
    source: 'mock-ai',
    createdAt: '2026-06-19T08:18:00+08:00',
    updatedAt: '2026-06-19T08:18:00+08:00',
  },
  {
    id: 'evt-patrol-roof-alert',
    type: 'patrol_risk',
    title: '天台高风险区域需二次复核',
    summary: '巡检策略触发高风险提醒，待安保查看。',
    level: 'high',
    status: 'reviewing',
    schoolId: 'school-hz-01',
    relatedPointId: 'point-roof-area',
    ownerUserId: 'admin-chen',
    source: 'mock-ai',
    createdAt: '2026-06-19T08:31:00+08:00',
    updatedAt: '2026-06-19T08:33:00+08:00',
  },
  {
    id: 'evt-emotion-group-alert',
    type: 'emotion_alert',
    title: '七年级二班群体情绪波动待复核',
    summary: '群体趋势较平时偏低，请心理老师复核。',
    level: 'medium',
    status: 'reviewing',
    schoolId: 'school-hz-01',
    classId: 'class-g7-2',
    ownerUserId: 'teacher-psy',
    source: 'mock-ai',
    createdAt: '2026-06-19T08:40:00+08:00',
    updatedAt: '2026-06-19T08:40:00+08:00',
  },
  {
    id: 'evt-notice-delivery',
    type: 'notice_delivery',
    title: '班级通知送达率 98%',
    summary: '家长通知通道畅通，当前仅 1 位家长未读。',
    level: 'low',
    status: 'closed',
    schoolId: 'school-hz-01',
    classId: 'class-g7-2',
    ownerUserId: 'teacher-lin',
    source: 'system',
    createdAt: '2026-06-19T08:25:00+08:00',
    updatedAt: '2026-06-19T08:25:00+08:00',
  },
  {
    id: 'evt-parent-feedback',
    type: 'parent_feedback',
    title: '家长反馈待回复',
    summary: '家长询问周五活动集合时间。',
    level: 'low',
    status: 'pending',
    schoolId: 'school-hz-01',
    classId: 'class-g7-2',
    actorUserId: 'parent-zhangnvshi',
    ownerUserId: 'teacher-lin',
    source: 'parent',
    createdAt: '2026-06-19T08:27:00+08:00',
    updatedAt: '2026-06-19T08:27:00+08:00',
  },
  {
    id: 'evt-manual-review',
    type: 'manual_review',
    title: '心理关注线索待人工复核',
    summary: '需要心理老师进一步确认并决定是否跟进。',
    level: 'medium',
    status: 'reviewing',
    schoolId: 'school-hz-01',
    classId: 'class-g7-2',
    ownerUserId: 'teacher-psy',
    source: 'manual',
    createdAt: '2026-06-19T08:42:00+08:00',
    updatedAt: '2026-06-19T08:42:00+08:00',
  },
];
